//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1430683_ASG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.GVGCarts = new HashSet<GVGCart>();
        }
    
        public int Id { get; set; }
        public int GpuId { get; set; }
        public string GpuName { get; set; }
        public Nullable<int> Price { get; set; }
        public string Descriptionofgpu { get; set; }
        public string Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GVGCart> GVGCarts { get; set; }
        public virtual ProductSpec ProductSpec { get; set; }
        public object ID { get; internal set; }
    }
}
