//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1430683_CO5027.App_Code
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_1430683_co5027_productEntities1 : DbContext
    {
        public db_1430683_co5027_productEntities1()
            : base("name=db_1430683_co5027_productEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GVGCart> GVGCarts { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductSpec> ProductSpecs { get; set; }
    }
}
