//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1430683_CO5027.App_Code
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductSpec
    {
        public int Id { get; set; }
        public int GpuId { get; set; }
        public string BaseClock { get; set; }
        public string BoostClock { get; set; }
        public string VramMemory { get; set; }
        public string VideoOutput { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
